-- ==============================================================================
-- SISTEMA COSTEÑITA — Esquema de Base de Datos PostgreSQL / Supabase (3FN)
-- Microempresa de Acopio y Comercialización de Miel — Villa Montes, Bolivia
-- ==============================================================================

-- 1. TABLA: PRODUCTO (Catálogo de Miel y Derivados)
CREATE TABLE IF NOT EXISTS producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    presentacion VARCHAR(50) NOT NULL,
    precio_venta NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (precio_venta >= 0),
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_producto_nombre_presentacion UNIQUE (nombre, presentacion)
);

-- 2. TABLA: PROVEEDOR (Apicultores locales de Villa Montes y alrededores)
CREATE TABLE IF NOT EXISTS proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL UNIQUE,
    localidad VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA: INVENTARIO (Relación 1:1 con Producto)
CREATE TABLE IF NOT EXISTS inventario (
    id_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL UNIQUE REFERENCES producto(id_producto) ON DELETE CASCADE,
    stock_actual NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    unidad_medida VARCHAR(20) NOT NULL DEFAULT 'UNIDAD' CHECK (unidad_medida IN ('GRAMOS', 'KG', 'UNIDAD')),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLA: COMPRA (Acopio de miel a proveedores - Gestión por Peso)
CREATE TABLE IF NOT EXISTS compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    cantidad NUMERIC(10, 2) NOT NULL CHECK (cantidad > 0),
    unidad_medida VARCHAR(20) NOT NULL CHECK (unidad_medida IN ('GRAMOS', 'KG', 'UNIDAD')),
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA' CHECK (estado IN ('REGISTRADA', 'ANULADA')),
    id_proveedor BIGINT NOT NULL REFERENCES proveedor(id_proveedor),
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    precio_unitario NUMERIC(10, 2) DEFAULT 0,
    total NUMERIC(10, 2) DEFAULT 0,
    observaciones TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABLA: MOVIMIENTO_INVENTARIO (Kardex / Inalterabilidad de movimientos)
CREATE TABLE IF NOT EXISTS movimiento_inventario (
    id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE')),
    cantidad NUMERIC(10, 2) NOT NULL CHECK (cantidad > 0),
    unidad_medida VARCHAR(20) NOT NULL DEFAULT 'UNIDAD' CHECK (unidad_medida IN ('GRAMOS', 'KG', 'UNIDAD')),
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    motivo VARCHAR(200),
    id_referencia BIGINT, -- id_compra o id_venta según corresponda
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABLA: VENTA (Comercialización de miel a clientes)
CREATE TABLE IF NOT EXISTS venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    cliente VARCHAR(100) NOT NULL DEFAULT 'Cliente Mostrador',
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    cantidad NUMERIC(10, 2) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(10, 2) NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'COMPLETADA' CHECK (estado IN ('COMPLETADA', 'ANULADA')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- TRIGGERS Y FUNCIONES AUTOMÁTICAS
-- ==============================================================================

-- Función para inicializar inventario automáticamente al crear un producto
CREATE OR REPLACE FUNCTION fn_crear_inventario_producto()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO inventario (id_producto, stock_actual, unidad_medida)
    VALUES (NEW.id_producto, 0, 'UNIDAD')
    ON CONFLICT (id_producto) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_crear_inventario_producto ON producto;
CREATE TRIGGER trg_crear_inventario_producto
AFTER INSERT ON producto
FOR EACH ROW
EXECUTE FUNCTION fn_crear_inventario_producto();

-- Función para actualizar stock tras un movimiento de inventario
CREATE OR REPLACE FUNCTION fn_actualizar_stock_movimiento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.tipo = 'ENTRADA' THEN
        UPDATE inventario
        SET stock_actual = stock_actual + NEW.cantidad,
            updated_at = NOW()
        WHERE id_producto = NEW.id_producto;
    ELSIF NEW.tipo = 'SALIDA' THEN
        -- Verificar que haya stock suficiente
        IF (SELECT stock_actual FROM inventario WHERE id_producto = NEW.id_producto) < NEW.cantidad THEN
            RAISE EXCEPTION 'Stock insuficiente para realizar la salida del producto ID %', NEW.id_producto;
        END IF;

        UPDATE inventario
        SET stock_actual = stock_actual - NEW.cantidad,
            updated_at = NOW()
        WHERE id_producto = NEW.id_producto;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_actualizar_stock_movimiento ON movimiento_inventario;
CREATE TRIGGER trg_actualizar_stock_movimiento
AFTER INSERT ON movimiento_inventario
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_stock_movimiento();

-- ==============================================================================
-- POLÍTICAS ROW LEVEL SECURITY (RLS) PARA SUPABASE
-- ==============================================================================
ALTER TABLE producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedor ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimiento_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura y escritura pública/autenticada
CREATE POLICY "Permitir acceso completo a producto" ON producto FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acceso completo a proveedor" ON proveedor FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acceso completo a inventario" ON inventario FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acceso completo a compra" ON compra FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acceso completo a movimiento_inventario" ON movimiento_inventario FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acceso completo a venta" ON venta FOR ALL USING (true) WITH CHECK (true);
