-- ==============================================================================
-- SISTEMA COSTEÑITA — Esquema de Base de Datos PostgreSQL / Supabase (3FN)
-- Cumplimiento de Normativa ASFI (Libro 3° Tít. VII), Ley 164 y Art. 363 ter C.P.
-- Microempresa de Acopio y Comercialización de Miel — Villa Montes, Bolivia
-- ==============================================================================

-- 0. EXTENSIONES DE SEGURIDAD Y CRIPTOGRAFÍA
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==============================================================================
-- 1. TABLA DE AUDITORÍA INALTERABLE (Normativa ASFI / Ley 164 Art. 79)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS logs_auditoria (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(50) NOT NULL,
    operacion VARCHAR(10) NOT NULL CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE', 'SELECT')),
    usuario_id UUID DEFAULT auth.uid(),
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    hash_anterior TEXT,
    hash_integridad TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger de Inalterabilidad Estricta: Prohibir cualquier UPDATE o DELETE en logs_auditoria
CREATE OR REPLACE FUNCTION fn_bloquear_alteracion_auditoria()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Operación denegada: Los registros de la tabla logs_auditoria son inalterables e indelebles según la normativa ASFI y la Ley N° 164 Art. 79.';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_bloquear_alteracion_auditoria ON logs_auditoria;
CREATE TRIGGER trg_bloquear_alteracion_auditoria
BEFORE UPDATE OR DELETE ON logs_auditoria
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_alteracion_auditoria();

-- ==============================================================================
-- 2. TABLAS DE DOMINIO DE NEGOCIO (Normalizadas en 3FN)
-- ==============================================================================

-- TABLA: PRODUCTO (Catálogo de Miel y Derivados)
CREATE TABLE IF NOT EXISTS producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    presentacion VARCHAR(50) NOT NULL,
    precio_venta NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (precio_venta >= 0),
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_producto_nombre_presentacion UNIQUE (nombre, presentacion)
);

-- TABLA: PROVEEDOR (Apicultores locales con PII Protegido)
CREATE TABLE IF NOT EXISTS proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(200) NOT NULL UNIQUE, -- Almacena dato sensible cifrado o enmascarado
    localidad VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: INVENTARIO (Relación 1:1 con Producto)
CREATE TABLE IF NOT EXISTS inventario (
    id_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL UNIQUE REFERENCES producto(id_producto) ON DELETE CASCADE,
    stock_actual NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    unidad_medida VARCHAR(20) NOT NULL DEFAULT 'UNIDAD' CHECK (unidad_medida IN ('GRAMOS', 'KG', 'UNIDAD')),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: COMPRA (Acopio de miel a proveedores - Gestión por Peso)
CREATE TABLE IF NOT EXISTS compra (
    id_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    cantidad NUMERIC(10, 2) NOT NULL CHECK (cantidad > 0),
    unidad_medida VARCHAR(20) NOT NULL CHECK (unidad_medida IN ('GRAMOS', 'KG', 'UNIDAD')),
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA' CHECK (estado IN ('REGISTRADA', 'ANULADA')),
    id_proveedor BIGINT NOT NULL REFERENCES proveedor(id_proveedor),
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    precio_unitario NUMERIC(10, 2) DEFAULT 0,
    total NUMERIC(10, 2) DEFAULT 0,
    observaciones TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: MOVIMIENTO_INVENTARIO (Kardex / Inalterabilidad de movimientos)
CREATE TABLE IF NOT EXISTS movimiento_inventario (
    id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE')),
    cantidad NUMERIC(10, 2) NOT NULL CHECK (cantidad > 0),
    unidad_medida VARCHAR(20) NOT NULL DEFAULT 'UNIDAD' CHECK (unidad_medida IN ('GRAMOS', 'KG', 'UNIDAD')),
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    motivo VARCHAR(200),
    id_referencia BIGINT, -- id_compra o id_venta según corresponda
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: VENTA (Comercialización de miel a clientes)
CREATE TABLE IF NOT EXISTS venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    cliente VARCHAR(100) NOT NULL DEFAULT 'Cliente Mostrador',
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    cantidad NUMERIC(10, 2) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(10, 2) NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'COMPLETADA' CHECK (estado IN ('COMPLETADA', 'ANULADA')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 3. FUNCIONES DE CRIPTOGRAFÍA Y SEGURIDAD (pgcrypto)
-- ==============================================================================

-- Función helper para cifrar texto sensible (Teléfono / PII)
CREATE OR REPLACE FUNCTION fn_cifrar_texto(p_texto TEXT)
RETURNS TEXT AS $$
BEGIN
    IF p_texto IS NULL OR p_texto = '' THEN
        RETURN p_texto;
    END IF;
    RETURN encode(pgp_sym_encrypt(p_texto, 'CLAVE_SECRETA_COSTENITA_ASFI_2026'), 'base64');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Función helper para descifrar texto sensible (Teléfono / PII)
CREATE OR REPLACE FUNCTION fn_descifrar_texto(p_cifrado TEXT)
RETURNS TEXT AS $$
BEGIN
    IF p_cifrado IS NULL OR p_cifrado = '' THEN
        RETURN p_cifrado;
    END IF;
    BEGIN
        RETURN pgp_sym_decrypt(decode(p_cifrado, 'base64'), 'CLAVE_SECRETA_COSTENITA_ASFI_2026');
    EXCEPTION WHEN OTHERS THEN
        -- Si el texto no está encriptado previamente, retorna el valor plano para mantener retrocompatibilidad
        RETURN p_cifrado;
    END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==============================================================================
-- 4. SISTEMA DE AUDITORÍA AUTOMÁTICA CON HASH ENCADENADO (SHA-256)
-- ==============================================================================

CREATE OR REPLACE FUNCTION fn_auditar_transaccion()
RETURNS TRIGGER AS $$
DECLARE
    v_hash_ant TEXT;
    v_hash_nuevo TEXT;
    v_datos_ant JSONB := NULL;
    v_datos_nuev JSONB := NULL;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        v_datos_ant := to_jsonb(OLD);
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        v_datos_nuev := to_jsonb(NEW);
    END IF;

    -- Obtener el último hash para el encadenamiento criptográfico (Bloque de auditoría ASFI)
    SELECT hash_integridad INTO v_hash_ant
    FROM logs_auditoria
    ORDER BY id_log DESC
    LIMIT 1;

    IF v_hash_ant IS NULL THEN
        v_hash_ant := 'GENESIS_COSTENITA_ASFI_2026';
    END IF;

    -- Generar SHA-256 encadenado combinando tabla, operación, usuario, datos y marca temporal
    v_hash_nuevo := encode(
        digest(
            v_hash_ant ||
            TG_TABLE_NAME ||
            TG_OP ||
            COALESCE(auth.uid()::text, 'ANONYMOUS_USER') ||
            COALESCE(v_datos_ant::text, '{}') ||
            COALESCE(v_datos_nuev::text, '{}') ||
            NOW()::text,
            'sha256'
        ),
        'hex'
    );

    INSERT INTO logs_auditoria (
        tabla_afectada,
        operacion,
        usuario_id,
        datos_anteriores,
        datos_nuevos,
        hash_anterior,
        hash_integridad
    ) VALUES (
        TG_TABLE_NAME,
        TG_OP,
        auth.uid(),
        v_datos_ant,
        v_datos_nuev,
        v_hash_ant,
        v_hash_nuevo
    );

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Disparadores de Auditoría en Tablas del Sistema
DROP TRIGGER IF EXISTS trg_audit_producto ON producto;
CREATE TRIGGER trg_audit_producto AFTER INSERT OR UPDATE OR DELETE ON producto FOR EACH ROW EXECUTE FUNCTION fn_auditar_transaccion();

DROP TRIGGER IF EXISTS trg_audit_proveedor ON proveedor;
CREATE TRIGGER trg_audit_proveedor AFTER INSERT OR UPDATE OR DELETE ON proveedor FOR EACH ROW EXECUTE FUNCTION fn_auditar_transaccion();

DROP TRIGGER IF EXISTS trg_audit_inventario ON inventario;
CREATE TRIGGER trg_audit_inventario AFTER INSERT OR UPDATE OR DELETE ON inventario FOR EACH ROW EXECUTE FUNCTION fn_auditar_transaccion();

DROP TRIGGER IF EXISTS trg_audit_compra ON compra;
CREATE TRIGGER trg_audit_compra AFTER INSERT OR UPDATE OR DELETE ON compra FOR EACH ROW EXECUTE FUNCTION fn_auditar_transaccion();

DROP TRIGGER IF EXISTS trg_audit_movimiento_inventario ON movimiento_inventario;
CREATE TRIGGER trg_audit_movimiento_inventario AFTER INSERT OR UPDATE OR DELETE ON movimiento_inventario FOR EACH ROW EXECUTE FUNCTION fn_auditar_transaccion();

DROP TRIGGER IF EXISTS trg_audit_venta ON venta;
CREATE TRIGGER trg_audit_venta AFTER INSERT OR UPDATE OR DELETE ON venta FOR EACH ROW EXECUTE FUNCTION fn_auditar_transaccion();

-- ==============================================================================
-- 5. INALTERABILIDAD DE REGISTROS COMERCIALES CERRADOS (ASFI / Cód. Comercio)
-- ==============================================================================

CREATE OR REPLACE FUNCTION fn_bloquear_modificacion_registros_cerrados()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Operación denegada: Las transacciones de compra, venta o inventario no se pueden eliminar físicamente. Registre una anulación para preservar la inalterabilidad contable (Código de Comercio Art. 40, ASFI).';
    ELSIF TG_OP = 'UPDATE' AND OLD.estado IN ('REGISTRADA', 'COMPLETADA', 'ANULADA') AND NEW.estado = OLD.estado THEN
        IF OLD.total <> NEW.total OR OLD.cantidad <> NEW.cantidad OR OLD.id_producto <> NEW.id_producto THEN
            RAISE EXCEPTION 'Operación denegada: No está permitido alterar retroactivamente precios ni cantidades de transacciones comerciales ya cerradas (Normativa ASFI / Ley N° 164).';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_bloquear_modificacion_compra ON compra;
CREATE TRIGGER trg_bloquear_modificacion_compra
BEFORE UPDATE OR DELETE ON compra
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_modificacion_registros_cerrados();

DROP TRIGGER IF EXISTS trg_bloquear_modificacion_venta ON venta;
CREATE TRIGGER trg_bloquear_modificacion_venta
BEFORE UPDATE OR DELETE ON venta
FOR EACH ROW
EXECUTE FUNCTION fn_bloquear_modificacion_registros_cerrados();

-- ==============================================================================
-- 6. TRIGGERS Y FUNCIONES DE NEGOCIO (Inventario Automático)
-- ==============================================================================

CREATE OR REPLACE FUNCTION fn_crear_inventario_producto()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO inventario (id_producto, stock_actual, unidad_medida)
    VALUES (NEW.id_producto, 0, 'UNIDAD')
    ON CONFLICT (id_producto) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_crear_inventario_producto ON producto;
CREATE TRIGGER trg_crear_inventario_producto
AFTER INSERT ON producto
FOR EACH ROW
EXECUTE FUNCTION fn_crear_inventario_producto();

CREATE OR REPLACE FUNCTION fn_actualizar_stock_movimiento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.tipo = 'ENTRADA' THEN
        UPDATE inventario
        SET stock_actual = stock_actual + NEW.cantidad,
            updated_at = NOW()
        WHERE id_producto = NEW.id_producto;
    ELSIF NEW.tipo = 'SALIDA' THEN
        IF (SELECT stock_actual FROM inventario WHERE id_producto = NEW.id_producto) < NEW.cantidad THEN
            RAISE EXCEPTION 'Stock insuficiente para realizar la salida del producto ID %', NEW.id_producto;
        END IF;

        UPDATE inventario
        SET stock_actual = stock_actual - NEW.cantidad,
            updated_at = NOW()
        WHERE id_producto = NEW.id_producto;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_actualizar_stock_movimiento ON movimiento_inventario;
CREATE TRIGGER trg_actualizar_stock_movimiento
AFTER INSERT ON movimiento_inventario
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_stock_movimiento();

-- ==============================================================================
-- 7. POLÍTICAS SEGURAS ROW LEVEL SECURITY (RLS PARA SUPABASE)
-- ==============================================================================
ALTER TABLE producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedor ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimiento_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_auditoria ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas inseguras públicas
DROP POLICY IF EXISTS "Permitir acceso completo a producto" ON producto;
DROP POLICY IF EXISTS "Permitir acceso completo a proveedor" ON proveedor;
DROP POLICY IF EXISTS "Permitir acceso completo a inventario" ON inventario;
DROP POLICY IF EXISTS "Permitir acceso completo a compra" ON compra;
DROP POLICY IF EXISTS "Permitir acceso completo a movimiento_inventario" ON movimiento_inventario;
DROP POLICY IF EXISTS "Permitir acceso completo a venta" ON venta;

-- Políticas de seguridad controladas
CREATE POLICY "Permitir lectura en producto" ON producto FOR SELECT USING (true);
CREATE POLICY "Permitir escritura en producto a autenticados" ON producto FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir lectura en proveedor" ON proveedor FOR SELECT USING (true);
CREATE POLICY "Permitir escritura en proveedor a autenticados" ON proveedor FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir lectura en inventario" ON inventario FOR SELECT USING (true);
CREATE POLICY "Permitir escritura en inventario a autenticados" ON inventario FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir lectura en compra" ON compra FOR SELECT USING (true);
CREATE POLICY "Permitir escritura en compra a autenticados" ON compra FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir lectura en movimiento_inventario" ON movimiento_inventario FOR SELECT USING (true);
CREATE POLICY "Permitir escritura en movimiento_inventario a autenticados" ON movimiento_inventario FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir lectura en venta" ON venta FOR SELECT USING (true);
CREATE POLICY "Permitir escritura en venta a autenticados" ON venta FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir lectura de auditoria a autenticados" ON logs_auditoria FOR SELECT TO authenticated USING (true);
