@startuml HU01_Casos_Uso

left to right direction

actor "Responsable de Costeñita" as Responsable

rectangle "Sistema de Gestión Costeñita" {

    usecase "Registrar producto" as UC_Registrar
    usecase "Validar datos del producto" as UC_Validar
    usecase "Verificar producto\nduplicado" as UC_Verificar
    usecase "Guardar producto" as UC_Guardar
    usecase "Mostrar error por\nproducto duplicado" as UC_Error
}

Responsable --> UC_Registrar

UC_Registrar .> UC_Validar : <<include>>
UC_Registrar .> UC_Verificar : <<include>>
UC_Registrar .> UC_Guardar : <<include>>

UC_Error .> UC_Registrar : <<extend>>

@enduml
